import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="  h-16  flex-1 bg-white text-black">
          <div className="mx-auto flex h-full max-w-4xl items-center justify-between ">
            <ul className="flex flex-1 items-center gap-5">
              <li>News</li>
              <li>Location</li>
              <li>Services</li>
            </ul>
            <div className="flex flex-1 items-center justify-center">
              <Image
                src={"logo.svg"}
                alt="logo"
                width={136}
                height={57}
                style={{ width: "auto", height: "auto" }}
              />
            </div>
            <div className="flex flex-1 items-center justify-end gap-8">
              {/* <div>P</div> */}
              <button className="flex items-center justify-center gap-3 rounded-xl bg-[#002172] px-3 py-2 text-white">
                Join Us
              </button>
              <button className="flex items-center justify-center gap-2 rounded-xl border border-[#002172] px-3 py-2 text-sm">
                Sign In
              </button>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
